name: Build and Release LogViewer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        host: 'linux'

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake

    - name: Create Build Directory
      run: mkdir build

    - name: Configure with CMake
      run: |
        cd build
        cmake ..

    - name: Build LogViewer
      run: |
        cd build
        make

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload compiled binaries
      uses: actions/upload-artifact@v3
      with:
        name: LogViewer
        path: build/LogViewer

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/LogViewer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
